name: Master CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, lint and test
      run: |
        yarn
        yarn lint
        yarn build --no-unsafe-inline
      env:
        CI: true

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@5711a203b3207eb1c6cebec6ac2152ab210ec3ae
      env:
        PRODUCTION_PORT: ${{secrets.PRODUCTION_PORT}}
        BROADCAST_NETWORK: ${{secrets.BROADCAST_NETWORK}}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: PRODUCTION_PORT,BROADCAST_NETWORK
        script: |
          cd ~/hivesigner-ui
          git pull origin main
          git checkout main
          yarn
          yarn build --no-unsafe-inline
          export PORT=$PRODUCTION_PORT
          pm2 reload master
